### ISSUE TITLE
Spec are not compatible with program instructions

### ISSUE THREAD

**Issue by yelbuod** [XUANTIE-RV/riscv-matrix-extension-spec#11]
when I use demos/gemm program and I found `madd.s.mx` instruction in the disassembly , but it cannot be found in the spec version 0.4, 12/2023. And I also found that the instruction format of `madd.s.mm` in the spec is `0001_1000_ms2_ms1_md_func3_1000_0010_1011`. But the format in program disassembly and CPF analysis data is `0011_0000_ms2_ms1_md_func3_1000_0010_1011`. 
Similar problems exist with other instructions like `madd.s.mv.i` has `0001_1010_ms2_ms1_md_func3_1000_0010_1011` in the spec but `0011_0100_ms2_ms1_md_func3_1000_0010_1011` in the program disassembly and CPF result. I am wondering if there is any error or version mismatch here. Thanks.

**Comment by QJtaibai** [comment]
The current toolchain only supports v0.3.  The development of subsequent versions is still ongoing.
