### ISSUE TITLE
qemu-riscv64: can't apply global rv64-riscv-cpu.rlen=128: Property 'rv64-riscv-cpu.rlen' not found

### ISSUE THREAD

**Issue by yelbuod** [XUANTIE-RV/riscv-matrix-extension-spec#8]
when I compile and install qemu as README description
```
cd xuantie-gnu-toolchain/
git submodule update --init
mkdir qemu/build
cd qemu/build
../configure --target-list="riscv32-linux-user,riscv64-linux-user"
make
```
then I get the 'qemu-riscv64' in qemu/build, so I try to run qemu at 'xuantie-gnu-toolchain/qemu/build' by:
```
./qemu-riscv64 -cpu rv64,x-v=true,vext_spec=v1.0,vlen=128,x-matrix=on,rlen=128 ../../../demos/gemm/gemm_int8.elf
```
But get the error "qemu-riscv64: can't apply global rv64-riscv-cpu.rlen=128: Property 'rv64-riscv-cpu.rlen' not found", if there something wrong or qemu version is uncompatible with this command? qemu commit id is  376ac85 as this resps.

**Comment by QJtaibai** [comment]
Are there still issues after updating the file?

**Comment by yelbuod** [comment]
It worked successfully after the update. Thank you.
